"""empty message

Revision ID: 52d9139f8808
Revises: 9cee29ef3e99
Create Date: 2019-12-02 11:44:26.314915

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '52d9139f8808'
down_revision = '9cee29ef3e99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('okr_kr',
    sa.Column('_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('startnum', sa.Integer(), nullable=False),
    sa.Column('endnum', sa.Integer(), nullable=False),
    sa.Column('confidencenum', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('okr_o',
    sa.Column('_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('startdate', sa.DateTime(), nullable=True),
    sa.Column('enddate', sa.DateTime(), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('createuser', sa.Integer(), nullable=False),
    sa.Column('state', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['createuser'], ['sys_user_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sys_organization',
    sa.Column('_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['sys_user_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('sys_user_profile', sa.Column('_time', sa.DateTime(), nullable=True))
    op.drop_column('sys_user_profile', 'create_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sys_user_profile', sa.Column('create_time', mysql.DATETIME(), nullable=True))
    op.drop_column('sys_user_profile', '_time')
    op.drop_table('sys_organization')
    op.drop_table('okr_o')
    op.drop_table('okr_kr')
    # ### end Alembic commands ###
