"""empty message

Revision ID: d88c20152944
Revises: 8e068f29d381
Create Date: 2019-12-15 17:42:51.174402

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd88c20152944'
down_revision = '8e068f29d381'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User_Organization',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['Organization.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], )
    )
    op.add_column('OKR_KR', sa.Column('okr_o_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'OKR_KR', 'OKR_O', ['okr_o_id'], ['id'])
    op.add_column('OKR_O', sa.Column('organization_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'OKR_O', 'Organization', ['organization_id'], ['id'])
    op.add_column('Organization', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_constraint('Organization_ibfk_1', 'Organization', type_='foreignkey')
    op.create_foreign_key(None, 'Organization', 'User', ['user_id'], ['id'])
    op.drop_column('Organization', 'admin_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Organization', sa.Column('admin_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'Organization', type_='foreignkey')
    op.create_foreign_key('Organization_ibfk_1', 'Organization', 'User', ['admin_id'], ['id'])
    op.drop_column('Organization', 'user_id')
    op.drop_constraint(None, 'OKR_O', type_='foreignkey')
    op.drop_column('OKR_O', 'organization_id')
    op.drop_constraint(None, 'OKR_KR', type_='foreignkey')
    op.drop_column('OKR_KR', 'okr_o_id')
    op.drop_table('User_Organization')
    # ### end Alembic commands ###
